# Main config file for icon theme.
theme = "hugo-icon"
baseURL = "https://igordub.github.io/look-back/"
languageCode = "en-US"
title = "Look Back"

# Metadata
[params]
  author = "Igors Dubanevics"
  description = "Look Back foundation official website."

# Hero section (from here on is for icon theme)
[params.hero]
  img = "images/hero_bg.jpg"
  title = "⠠⠇ | Look Back"
  description = "Here To Help"

# Navigation section
[params.nav]
  mission = "Our Mission"
  # services = "Services"
  team = "The Team"
  contact = "Get In Touch"
  # Include logo instead if HOME:
  # logo = "path/to/logo"

# Mission section
[params.mission]
  enable = true

  [params.mission.images]
    enable = true

    [[params.mission.images.list]]
      img = "images/img_3.jpg"
    [[params.mission.images.list]]
      img = "images/img_2.jpg"
    [[params.mission.images.list]]
      img = "images/img_1.jpg"
    [[params.mission.images.list]]
      img = "images/img_4.jpg"

  [[params.mission.item]]
    weight = 1
    name = "mission"
    title = "Mission"
    subtitle = "Our mission is to raise awareness in the community about the reasonable use of resources and to help people in need."
    description = "<p>Our mission is to raise awareness in the community about the reasonable use of resources and to help people in need.</p><ul class='checked'><li>Web Development</li><li>User Interface Experts</li><li>Pixel Perfect Design</li></ul><p><a href='#' class='btn btn-primary btn-outline fh5co-content-nav' data-nav-section='contact'>Get In Touch</a></p>"

  [[params.mission.item]]
    weight = 2
    name = "projects"
    title = "Projects"
    subtitle = "TBC"
    description = "<p>TBC</p><ul class='checked'><li>Free HTML5 Templates</li><li>Free Bootstrap Templates</li><li>Free HTML5 Bootstrap Templates</li></ul><p><a href='#' class='btn btn-primary btn-outline fh5co-content-nav' data-nav-section='contact'>Get In Touch</a></p>"

  [[params.mission.item]]
    weight = 3
    name = "partners"
    title = "Partners"
    subtitle = "TBC"
    description = "<p>TBC</p><ul class='checked'><li>Web Development</li><li>User Interface Experts</li><li>Pixel Perfect Design</li></ul><p><a href='#' class='btn btn-primary btn-outline fh5co-content-nav' data-nav-section='contact'>Get In Touch</a></p>"

# Services section
[params.services]
  enable = false
  video = false
  vidlink = "https://vimeo.com/channels/staffpicks/93951774"
  title = "Watch What We Do"
  description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

  [[params.services.item]]
    icon = "icon-present"
    title = "Web Development"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

  [[params.services.item]]
    icon = "icon-eye"
    title = "Retina Ready"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

  [[params.services.item]]
    icon = "icon-paper-plane"
    title = "Light Speed"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

  [[params.services.item]]
    icon = "icon-pencil"
    title = "Copyrighting"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

  [[params.services.item]]
    icon = "icon-rocket"
    title = "Load Fast"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

  [[params.services.item]]
    icon = "icon-support"
    title = "Customer Support"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

# Work section
[params.work]
  enable = true

  [[params.work.item]]
    title = "Look Back"
    subtitle = "Here to Help"
    img = "images/people_painting_01.jpg"

  [[params.work.item]]
    # title = "Consectetur adipisicing"
    # subtitle = "Web Design"
    img = "images/people_painting_02.jpg"

  [[params.work.item]]
    # title = "Consectetur adipisicing"
    # subtitle = "Web Design"
    img = "images/people_painting_03.jpg"

  [[params.work.item]]
    # title = "Consectetur adipisicing"
    # subtitle = "Web Design"
    img = "images/hospital_01.jpg"

  [[params.work.item]]
    # title = "Consectetur adipisicing"
    # subtitle = "Web Design"
    img = "images/hospital_02.jpg"

  [[params.work.item]]
    # title = "Consectetur adipisicing"
    # subtitle = "Web Design"
    img = "images/hospital_03.jpg"

  [[params.work.item]]
    # title = "Consectetur adipisicing"
    # subtitle = "Web Design"
    img = "images/hospital_door_01.jpg"

  [[params.work.item]]
    # title = "Consectetur adipisicing"
    # subtitle = "Web Design"
    img = "images/hospital_door_01.jpg"

# Team section
[params.team]
  enable = true
  title = "Meet The Team"
  # description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

  [[params.team.item]]
    name = "Artjoms Karabadžaks"
    position = "Member of the Board"
    description = " Operational support and planning officer. Co-Founder of Look Back. Experienced aircraft engineer with more than 10 years of freelance maintenance activities around Europe, travel expert, experienced in fast deployment and development in unknown area, socially active with positive attitude."
    img = "images/person1.jpg"
    # email = "#"
    # telephone = "#"
    # facebook = "#"
    # twitter = "#"
    # dribbble = "#"
    # instagram = "#"
    # github = "#"
    # linkedin = "#"
    # whatsapp = "#"

  [[params.team.item]]
    name = "Luiza Zagitova"
    position = "Chairman of the Board"
    description = "Formal representative of the organization, inspirational speaker and founder of the Look Back foundation. Experienced in accounting and taxing."
    img = "images/profile_LuizaZagitova.jpg"
    # email = "#"
    # telephone = "#"
    # facebook = "#"
    # twitter = "#"
    # dribbble = "#"
    # instagram = "#"
    # github = "#"
    # whatsapp = "#"

  [[params.team.item]]
    name = "Vlads Komarockis"
    position = "Member of the Board"
    description = "Financial planner and administrative work officer. Co-Founder of Look Back. Aspiring film producer, IT support specialist at Courthouse Agency of Republic of Latvia. Experienced volunteer and Erasmus+ participant. Polyglot."
    img = "images/profile_VladsKomarockis.jpg"
    # email = "#"
    # telephone = "#"
    # facebook = "#"
    # twitter = "#"
    # dribbble = "#"
    # instagram = "#"
    # github = "#"
    # whatsapp = "#"

  # [[params.team.item]]
  #   name = "Jason Doe"
  #   position = "Chief haranguer"
  #   description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
  #   img = "images/person3.jpg"
  #   email = "#"
  #   telephone = "#"
  #   facebook = "#"
  #   twitter = "#"
  #   dribbble = "#"
  #   instagram = "#"
  #   github = "#"
  #   whatsapp = "#"

# Contact section
[params.contact]
  enable = true
  title = "Get In Touch"
  message = "Please, enter your contact details and message below to reach out."
  name_placeholder = "Your name"
  email_placeholder = "Your email"
  email_disclaimer = "We'll never share your email with anyone else."
  message_placeholder = "Please enter a message."
  button_text = "Submit"

# Footer section
# Note here that the copyright and attribution statement must remain as part of the license agreement. If you wish to remove this, please contact freehtml5 and pay for a professional license.
[params.footer]
  enable = true
  note = "<p><small>&copy; 2016 Free HTML5 Template. All Rights Reserved. <br> Designed by <a href='http://freehtml5.co/' target='_blank'>FreeHTML5.co</a> Demo Images: <a href='http://pexels.com/' target='_blank'>Pexels</a><br>Hugo port by <a href='https://github.com/SteveLane/' target='_blank'>SteveLane</a></small></p>"
  github = "#"
  twitter = "#"
  facebook = "#"
  vine = "#"
  linkedin = "#"
  instagram = "#"
  
